# Generated by Django 5.2.8 on 2025-11-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ANALISTA', 'Analista'), ('AUDITOR', 'Auditor')], default='ANALISTA', max_length=20),
        ),
    ]
