# Generated by Django 5.2.8 on 2025-11-12 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cuentas', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportar'), ('UPLOAD', 'Cargar archivo')], max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('datos_anterior', models.JSONField(blank=True, help_text='Datos antes de la acción', null=True)),
                ('datos_nuevo', models.JSONField(blank=True, help_text='Datos después de la acción', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'creado_en'], name='cuentas_aud_usuario_e41900_idx'), models.Index(fields=['accion', 'creado_en'], name='cuentas_aud_accion_3c926f_idx'), models.Index(fields=['modelo', 'creado_en'], name='cuentas_aud_modelo_e4be3f_idx')],
            },
        ),
    ]
