# Generated by Django 5.2.6 on 2025-11-09 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificacionfiscal', '0001_initial'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='parametros.parametro'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='contribuyente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificacionfiscal.contribuyente'),
        ),
    ]
