# Generated by Django 5.2.8 on 2025-11-12 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacionfiscal', '0002_initial'),
        ('parametros', '0002_instrument_issuer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('AAA', 'AAA - Riesgo muy bajo'), ('AA', 'AA - Riesgo bajo'), ('A', 'A - Riesgo bajo a moderado'), ('BBB', 'BBB - Riesgo moderado'), ('BB', 'BB - Riesgo moderado a alto'), ('B', 'B - Riesgo alto'), ('CCC', 'CCC - Riesgo muy alto'), ('CC', 'CC - Riesgo muy alto'), ('C', 'C - Riesgo muy alto'), ('D', 'D - En incumplimiento')], max_length=10)),
                ('fecha_rating', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('outlook', models.CharField(choices=[('POSITIVO', 'Positivo'), ('ESTABLE', 'Estable'), ('NEGATIVO', 'Negativo')], default='ESTABLE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_ratings_creados', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_ratings', to='parametros.instrument')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_ratings', to='parametros.issuer')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'ordering': ['-fecha_rating'],
                'indexes': [models.Index(fields=['issuer', 'fecha_rating'], name='calificacio_issuer__adc03a_idx'), models.Index(fields=['instrument', 'fecha_rating'], name='calificacio_instrum_23fca4_idx'), models.Index(fields=['rating'], name='calificacio_rating_442139_idx'), models.Index(fields=['creado_en'], name='calificacio_creado__0804c7_idx')],
                'unique_together': {('issuer', 'instrument', 'fecha_rating')},
            },
        ),
    ]
