# Generated by Django 5.2.8 on 2025-11-15 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacionfiscal', '0003_taxrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='bulk_uploads/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_ok', models.IntegerField(default=0)),
                ('filas_error', models.IntegerField(default=0)),
                ('resumen_errores', models.JSONField(blank=True, default=dict)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga Masiva',
                'verbose_name_plural': 'Cargas Masivas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.IntegerField()),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error')], max_length=10)),
                ('mensaje_error', models.CharField(blank=True, max_length=500)),
                ('datos', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bulk_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calificacionfiscal.bulkupload')),
            ],
            options={
                'verbose_name': 'Item de Carga Masiva',
                'verbose_name_plural': 'Items de Carga Masiva',
                'ordering': ['numero_fila'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkupload',
            index=models.Index(fields=['usuario', 'estado'], name='calificacio_usuario_b2e0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkupload',
            index=models.Index(fields=['creado_en'], name='calificacio_creado__9d7460_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploaditem',
            index=models.Index(fields=['bulk_upload', 'estado'], name='calificacio_bulk_up_680949_idx'),
        ),
    ]
