# Generated by Django 5.2.8 on 2025-11-17 03:56

from django.conf import settings
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('calificacionfiscal', '0004_bulkupload_bulkuploaditem_and_more'),
        ('parametros', '0002_instrument_issuer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrating',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Calificación Tributaria', 'verbose_name_plural': 'Calificaciones Tributarias'},
        ),
        migrations.RemoveIndex(
            model_name='taxrating',
            name='calificacio_issuer__adc03a_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxrating',
            name='calificacio_instrum_23fca4_idx',
        ),
        # Mover unique_together después de crear el campo 'valid_from'
        migrations.AddField(
            model_name='taxrating',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='taxrating',
            name='risk_level',
            field=models.CharField(choices=[('MUY_BAJO', 'Muy Bajo'), ('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('MUY_ALTO', 'Muy Alto')], default='MODERADO', max_length=20),
        ),
        migrations.AddField(
            model_name='taxrating',
            name='status',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='taxrating',
            name='valid_from',
            field=models.DateField(default=datetime.date(2025, 11, 17), verbose_name='Válido desde'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxrating',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Válido hasta'),
        ),
        migrations.AddIndex(
            model_name='taxrating',
            index=models.Index(fields=['issuer', 'valid_from'], name='calificacio_issuer__8017a4_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrating',
            index=models.Index(fields=['instrument', 'valid_from'], name='calificacio_instrum_761ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrating',
            index=models.Index(fields=['status'], name='calificacio_status_f11078_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxrating',
            unique_together={('issuer', 'instrument', 'valid_from')},
        ),
        migrations.RemoveField(
            model_name='taxrating',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='taxrating',
            name='fecha_rating',
        ),
        migrations.RemoveField(
            model_name='taxrating',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='taxrating',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='taxrating',
            name='outlook',
        ),
    ]
